---
name: Encode-Mapper
version: 1.6
author:
  - 'Otakar Smrz <otakar smrz mff cuni cz>'
abstract: Intuitive, yet efficient mappings for Encode
license: perl
requires:
  perl: 5.008
build_requires:
  Test::More: 0
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  Encode::Mapper:
    file: lib/Encode/Mapper.pm
    version: 1.6
resources:
  license: http://dev.perl.org/licenses/
